### ISSUE TITLE
I can't seem to get allowFileExt to work

### ISSUE THREAD

**Issue by Veljanovskii** [thetbw/jquery-uploader#3]
Here's how I initialize the plugin but the allowFileExt option doesn't work (I still can see and select any file type):
`InitializeUploaderPlugin: function () {
    $("#file-upload-button").uploader({
        multiple: true,
        autoUpload: false,
        allowFileExt: ['jpg', 'jpeg', 'png', 'gif', 'mp4']
    });
}`

Also, is there any option to limit the maximum number of files that can be added? Something like
`maxFiles: 5`

**Comment by thetbw** [comment]
i'm Sorry, the current version cannot do this yet. I will improve it at the next prompt

you can do like this
```javascript
$("#demo1").uploader({multiple: true, ajaxConfig: ajaxConfig, autoUpload: false})
        .on("file-add", (event, ...files) => {
            //In the current version, files should always be the same file, and I will fix this issue later
            
            //the event after file added
            //get now all files and limit the length
            let addedFiles = $("#demo1").uploader("uploadFiles")
            if (addedFiles.length > 5){
                // delete the file you just added
                $("#demo1").uploader("removeFiles",...(files.map(file => file.id)))
                //alert something
                //....
            }
            
            console.log(files)
            //limit the file ext
            for (let file of files){
                if (!file.name.endsWith('.jpg')){
                    // delete the file you just added
                    $("#demo1").uploader("removeFiles",file.id)
                    //alert something
                }
            }
        })
```

**Comment by Veljanovskii** [comment]
When can we expect you to add these options natively in the plugin?

**Comment by thetbw** [comment]
within two weeks.
I was quite surprised to learn that someone has been using my product.

**Comment by thetbw** [comment]
allowFileExt and maxLenght  are support
