### ISSUE TITLE
allowFileExt

### ISSUE THREAD

**Issue by artsem-pranko** [thetbw/jquery-uploader#4]
Hello my dear friend.
Thank you for your work.
There is a problem with the allowFileExt option.
Can u fix this or how i can fix this? In the previous issue your solution did not help.
Now I write attr accept for input in jquery.uploader.min.js
Could you also add a non-minified version of js to the archive.
Best wishes!

**Comment by thetbw** [comment]
I'll submit a fix tonight

**Comment by thetbw** [comment]
allowFileExt is support
