### ISSUE TITLE
upload()

### ISSUE THREAD

**Issue by pyhoon** [thetbw/jquery-uploader#6]
How can I use the upload method to upload the files by clicking on a submit button if I set the autoUpload to false?

**Comment by thetbw** [comment]
just call upload mothod like this
```html
<div>
<button id="upload">upload</button>
<input id="files"/>
</div>
<script>
$("#input").uploader({
    multiple: true,
    autoUpload:false,
    ajaxConfig: {
        url: "/upload"
    }
})
$("#upload").on("click",()=>{
  $("#input").uploader("upload")
})
</script>
```
[support methods](https://github.com/thetbw/jquery-uploader/blob/master/doc/methods.md)

**Comment by pyhoon** [comment]
Thanks for replying.

**Comment by pyhoon** [comment]
I decided to use autoUpload: true.
So it calls first API which return the image URL and then I submit this URL with my second API to make a new post with a Submit button. This is much simpler.
