### ISSUE TITLE
how to set the files array to update? 

### ISSUE THREAD

**Issue by dcalixto** [thetbw/jquery-uploader#7]
i'm trying to update the form with the files array maybe removing or add a file and update, but when i press update button in the logs show this **JSON::ParserError - Empty input (after ) at line 1, column 2 [parse.c:1058]** error

this what i've tried

to fix this parse error i tried to refreshPreviewFileList as you @thetbw mentioned on here [https://github.com/thetbw/jquery-uploader/issues/1 ](url) 

i tried to .serializeArray(); on uploadFiles and stringify the formdata even split the uploadFiles array. none of this worked to fix the ParserError, so someone can give a help?

```
$(document).ready(function () {
  $("#upload-input")
    .uploader({
      multiple: true,
      autoUpload: false,
      maxLength: 6,

      defaultValue:
        <%= @item.photos.map { |photo| { url: photo.image.url, name: photo.item.name } }.to_json.html_safe %>,
    })
    .on("file-remove", (event, files) => {
      console.log(files);
    });
});

$(document).ready(function () {
  $("#new_item").on("submit", function (event) {
    event.preventDefault(); // Prevent the default form submission

    // Manually submit the form after Uppy files have been added
    var form = this;
    var formdata = new FormData(form);

    //var formdata = $(this).serializeArray();

    var files = $("#upload-input").uploader("uploadFiles");

    $("#upload-input").uploader("refreshPreviewFileList");

    //$("#upload-input").uploader("refreshPreviewFileList");
    for (let i = 0; i < files.length; i++) {
      formdata.append("files[]", files[i].file);
    }

    //var data = JSON.stringify(files.serializeArray());

    //for (let i = 0; i < data.length; i++) {
    // formdata.append('files[]', data[i].file)

    //}

    // Submit the form using AJAX
    $.ajax({
      url: "/items/<%= @item.slug%>", // Change this URL to your endpoint
      method: "patch",
      data: formdata,

      contentType: false,
      processData: false,
      success: function (response) {
        console.log("Upload successful:", response);
        // Handle success as needed
      },
      error: function (response) {
        console.error("Error:", response);
        // Handle error as needed
      },

      xhr: function () {
        let xhr = new XMLHttpRequest();

        xhr.upload.addEventListener("progress", function (e) {
          let progressRate = (e.loaded / e.total) * 100;

          progressCallback(progressRate);
        });

        return xhr;
      },
    });
  });
});

```
![files-to-upload](https://github.com/thetbw/jquery-uploader/assets/1009077/e1e80694-b544-4f11-a851-4187c0b4439e)
![logs-error](https://github.com/thetbw/jquery-uploader/assets/1009077/7bd7faff-e981-4c0a-b6ba-2e3576281971)
![logs2-error](https://github.com/thetbw/jquery-uploader/assets/1009077/2eef7e5f-696f-412c-a0a6-d03bf889cf22)

**Comment by thetbw** [comment]
I didn't see where the logic of the update is, and which code the error is reported.
give some tips,
defaultValue cannot upload,it is not a file, `files[i].file` will be null when is defaultValue.

when add file you can call [handleFileAdd](https://github.com/thetbw/jquery-uploader/blob/master/src/uploader.js#L493) 

when romveFile ,you can call removeFiles ,like `$ele.uploader('removeFiles',id1,id2)`

>Is your error report from the server? Please let me see the complete request body

**Comment by dcalixto** [comment]
@thetbw when we remove files from `defaultValue` that not update the component `uploadFiles`? because the values of `files[i].file` seems to come from `files = $("#upload-input").uploader("uploadFiles");`
It's shrine https://github.com/shrinerb/shrine
Seems a not valid format json error 

```
  def uploaded_file(object)
          object = JSON.parse(object) if object.is_a?(String)
   end
```

![shrine-parse-error](https://github.com/thetbw/jquery-uploader/assets/1009077/cdb7c3e3-dc26-4581-9fed-ebb94017b435)
![parse-logs](https://github.com/thetbw/jquery-uploader/assets/1009077/2646e72b-cc83-4443-8bcc-907295b69c3b)

**Comment by thetbw** [comment]
`formdata` is not  json format,i don't know about ruby,this looks like a problem with your server

**Comment by dcalixto** [comment]
@thetbw  It seems like  working on a form that involves uploading files using the uploader plugin and then submitting the form via AJAX. The error found, JSON::ParserError - Empty input, suggests that there's an issue with the data being sent or processed on the server side. This error is usually raised when the server is expecting a JSON input but receives an empty string instead.

From your code, it seems like  trying to send the file data as FormData, which is the correct approach. However, there are a few things in your code that could be causing the issue. Let's go through your code and see if we can find any potential problems

**Comment by dcalixto** [comment]
@thetbw one doubt this **parent:** on **defaultOptions** what this for?
and **handleFileAdd** is for getting the uploaded files?

**Comment by thetbw** [comment]
It is advisable not to employ JSON to receive form data, as a prime example; The function handleFileAdd is designed to accept data of type File for file addition, rather than fetching the file; Please examine your browser's network interface to ensure that the AJAX request is successful and that the request body contains the file data, indicating that the client is functioning correctly.
The default option for the uploader is the value of defaultOption.
