### ISSUE TITLE
Allow to view other file format

### ISSUE THREAD

**Issue by pyhoon** [thetbw/jquery-uploader#8]
How can I modify the code to allow uploaded pdf or text file to be open or download instead of just showing a delete button?

**Comment by thetbw** [comment]
In code file
https://github.com/thetbw/jquery-uploader/blob/master/src/uploader.js

add a download or preview pdf button on line 223,
add the click event of the button on line 351,
final process the preview or download logic in the click event. parameters example, please refer to `handleFileView`.

**Comment by thetbw** [comment]
Immediately above:

`createFileCardEle` render html,
`refreshPreviewFileList` process event and other.

**Comment by pyhoon** [comment]
But I am using the dist/jquery.uploader.min.js file.
How do I minify the source?

**Comment by thetbw** [comment]
clone the project , edit source file. run `npm install` and `npm run build`  in project root folder to build finally js.
`npm` is the package management tool for `nodejs`

**Comment by pyhoon** [comment]
Thanks.
I am not good in js.
Just manage to open a pdf in new tab with 
`window.open(uploaderFile.url)`
